<a href="https://colab.research.google.com/github/cesarniyo/Credit-Card-Fraud-Detection-ANOMALY-DETECTION/blob/master/Python_Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Array Operations

What is an array?

An array is a **data structure** which can hold more than one value at time. It is a collection of elements of the SAME TYPE.
Each element/value has an index associated.

# Basic array manipulation

### Importing array module

In [0]:
import array
# import array as arr
#from array import *

In [0]:
a =array.array('i',[1,2,3,4,5])
print(a)

array('i', [1, 2, 3, 4, 5])


### Accessing array elements

In [0]:
a[2]

3

In [0]:
a[-2]

4

### Operation on Array




#### Finding the length of an array

In [0]:
len(a)

5

#### Adding elements

In [0]:
a.append(8)
print(a)

array('i', [1, 2, 3, 4, 5, 8])


In [0]:
a.extend([10,11,12])
print(a)

array('i', [1, 2, 3, 4, 5, 8, 10, 11, 12])


In [0]:
a.insert(2,70)
print(a)

array('i', [1, 2, 70, 3, 4, 5, 8, 10, 11, 12])


#### Removing elements

In [0]:
# remove elements at index 2
a.pop(2) 
a

array('i', [1, 2, 3, 4, 5, 8, 10, 11, 12])

In [0]:
# remove element 8
a.remove(8) 
a

array('i', [1, 2, 3, 4, 5, 10, 11, 12])

#### Array Concatenation

In [0]:
b=array.array('d',[1.0,2.0])
c=array.array('d',[3.0,4.0])
d=array.array('d')
d=b+c
d

array('d', [1.0, 2.0, 3.0, 4.0])

#### Slicing an array

In [0]:
print(d[0:2])


array('d', [1.0, 2.0])


In [0]:
print(d[0:-1])


array('d', [1.0, 2.0, 3.0])


In [0]:
print(d[::-1])

array('d', [4.0, 3.0, 2.0, 1.0])


#### Looping throuht an array

In [0]:
print([x for x in d[:-1]])

[1.0, 2.0, 3.0]


In [0]:
temp=0
while temp<len(d):
  print(d[temp])
  temp+=1

1.0
2.0
3.0
4.0


# Advanced array manipulation 1

In [0]:
import numpy as np

# Building an array using numpy
mydatashow=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(mydatashow)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [0]:
# Building an array without using numpy
mydata=([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(mydata)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [0]:
# printing each raw
for i in mydata:
   print(i)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]


In [0]:
# printing the number of raws available
for i in range(len(mydata)):
   print(i)

0
1
2
3


In [0]:
# printing the number of columns available
for j in range(len(mydata[0])):
   print(j)

0
1
2
3
4


In [0]:
# printing all element starting from raw 0 to the last one
for i in range(len(mydata)): 
  for j in range(len(mydata[0])):
    print(mydata[i][j])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [0]:
# printing all element from raw 0 to 2 /from column 1 to column 3
for i in range(0,3): 
  for j in range(1,4):
    print(mydata[i][j])

2
3
4
7
8
9
12
13
14


### Adding two Matrices

In [0]:
# Program to add two matrices
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]
for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### Multiplying two matrices

In [0]:
# Program to multiply two matrices 
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


### Dot product of two matrices

In [0]:
# Computing dot product of matrices

def dotpro(X,Y):
    if len(X[0])!=len(Y):
      return 'Required Matrices Dimension Error'
    else:
        # Initializing Result Matrix       
        N =len(Y[0]) #4 Declaring rows
        M =len(X) #3 Declaring columns 
        R = [[ 0 for i in range(N) ] for j in range(M)] 

        # R= [[0,0],
        #     [0,0]]

        # iterate through rows of X
        for i in range(len(X)):
          # iterate through columns of Y
          for j in range(len(Y[0])):
            # iterate through rows of Y
            for k in range(len(Y)):
                R[i][j]+=(X[i][k]*Y[k][j])
        return R

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]




print(np.array(dotpro(X,Y)))  
#print(np.dot(X,Y))

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


### Transpose a matrix

In [0]:
# Program to transpose a matrix 
X = [[12,7],
    [4 ,5],
    [3 ,8]]
result = [[0,0,0],
         [0,0,0]]
# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]
for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


### Program to count the number of each vowels

In [0]:
# Program to count the number of each vowels
# string of vowels
vowels = 'aeiou'
ip_str = 'Hello, have you tried our tutorial section yet?'
# make it suitable for caseless comparisions
ip_str = ip_str.casefold()
# make a dictionary with each vowel a key and value 0
count = {}.fromkeys(vowels,0)
# count the vowels
for char in ip_str:
   if char in count:
       count[char] += 1
print(count)

{'a': 2, 'e': 5, 'i': 3, 'o': 5, 'u': 3}


### Program to display the Fibonacci sequence up to n-th term

In [0]:
# Program to display the Fibonacci sequence up to n-th term
nterms = int(input("How many terms? "))
# first two terms
n1, n2 = 0, 1
count = 0
# check if the number of terms is valid
if nterms <= 0:
   print("Please enter a positive integer")
elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)
else:
   print("Fibonacci sequence:")
   while count < nterms:
       print(n1)
       nth = n1 + n2
       # update values
       n1 = n2
       n2 = nth
       count += 1

How many terms? 5
Fibonacci sequence:
0
1
1
2
3


### Program to check if a number is prime

In [0]:
a=int(input("enter number"))     
if a>1:
    for x in range(2,a):
        if(a%x)==0:
            print("not prime")
            break
        else:
            print("Prime")
else:
    print("not prime")

enter number5
Prime
Prime
Prime


### Program to check if a sequence is a Palindrome

In [0]:
a=input("enter sequence")
b=a[::-1]
if a==b:
    print("palindrome")
else:
    print("Not a Palindrome")

enter sequence1221
palindrome


### Program to count the number of capital letters in a file

In [0]:
with open(SOME_LARGE_FILE) as fh:
count = 0
text = fh.read()
for character in text:
    if character.isupper():
count += 1

### Sorting algorithm for a numerical dataset

In [0]:
list = ["1", "4", "0", "6", "9"]
list = [int(i) for i in list]
list.sort()
print (list)

[0, 1, 4, 6, 9]


# Advanced array manipulation 2

In [0]:
# Extracting intersection between 2 triangles applied to the dataframe
def intersection(mydata,triangle1,triangle2):
    firstlist=[]
    secondlist=[]
    for i in range(triangle1[0],triangle1[2]+1): # elements covered with 1st triangle
      for j in range(triangle1[1],triangle1[3]+1):
        firstlist.append(mydata[i][j])

    for i in range(triangle2[0],triangle2[2]+1): # elements covered with 2nd triangle
      for j in range(triangle2[1],triangle2[3]+1):
        secondlist.append(mydata[i][j])
 
    intersec = [value for value in firstlist if value in secondlist] #intersection of both sets
    return firstlist,secondlist,intersec



#returns the jaccard similarity between two lists
def jaccard_similarity(x,y):
    intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
    union_cardinality = len(set.union(*[set(x), set(y)]))
    return intersection_cardinality/float(union_cardinality)


triangle1=[0,1,2,3]
triangle2=[1,2,3,4]

firstlist,secondlist,intersec = intersection(mydata,triangle1,triangle2)
print(firstlist)
print(secondlist)
print(intersec)
print()
jaccard_similarity(firstlist,secondlist)

[2, 3, 4, 7, 8, 9, 12, 13, 14]
[8, 9, 10, 13, 14, 15, 18, 19, 20]
[8, 9, 13, 14]



0.2857142857142857

# Some about function

In [0]:
x = ['ID','State','Amount']
def func2(id_st_amt):
    # Unpack Values
    (Id,st,amt) = id_st_amt
    return amt

func2(x)

'Amount'